targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: lib/swagger_specs
          output_folder: lib/openapi
          enums_case_sensitive: true
          separate_models: true
